### ISSUE TITLE
Doesn't show cover image

### ISSUE THREAD

**Issue by MrArdillo** [sharenite/sharenite#53]
The games doesn't have a cover. Had i done something wrong? ![image](https://user-images.githubusercontent.com/77178902/198845809-2c1ed707-b3d8-47ff-be54-faf1f7368ce8.png)

**Comment by XenorPLxx** [comment]
It's expected, covers will be implemented as part of this task soon:tm:
 https://github.com/sharenite/playnite-sharenite/issues/4
