### ISSUE TITLE
Public Install Directory

### ISSUE THREAD

**Issue by Corbi** [sharenite/sharenite#63]
I think that the installation directory of the games shouldn't be public. The route could have things like usernames, real names or other sensitive information.

For example: D:\John\PiratedGames\

At least shouldn't be public by default.

**Comment by XenorPLxx** [comment]
Nothing about user's account is public by default, you have to set it to public (or friendly) by going into profile settings.
I plan to add more privacy settings in https://github.com/sharenite/sharenite/issues/31, I'll add it to the list.

**Comment by Corbi** [comment]
I know that the entire profile isn't public by default. I'm saying that if you mark it as public, you could be publishing some sensitive information by mistake, because the Installation Directory field can't be hidden in a public profile.

If this is going to change, it's ok.
